# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: forbid-new-submodules
  - repo: https://github.com/warpnet/salt-lint
    rev: v0.5.2
    hooks:
      - id: salt-lint
        files: '\.sls$'
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/markdownlint/markdownlint
    rev: ''
    hooks:
      - id: markdownlint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: git-check
  - repo: https://github.com/motet-a/jinjalint
    rev: ''
    hooks:
      - id: jinjalint
